language: python

sudo: false

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-django18
    - python: 3.4
      env: TOX_ENV=py34-django18
    - python: 2.7
      env: TOX_ENV=py27-django19
    - python: 3.4
      env: TOX_ENV=py34-django19
    - python: 3.5
      env: TOX_ENV=py35-django19
    - python: 2.7
      env: TOX_ENV=py27-django110
    - python: 3.4
      env: TOX_ENV=py34-django110
    - python: 3.5
      env: TOX_ENV=py35-django110
    - python: 2.7
      env: TOX_ENV=py27-django111
    - python: 3.4
      env: TOX_ENV=py34-django111
    - python: 3.5
      env: TOX_ENV=py35-django111
    - python: 3.6
      env: TOX_ENV=py36-django111
    - python: 3.5
      env: TOX_ENV=py35-djangomaster
    - python: 3.6
      env: TOX_ENV=py36-djangomaster
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py35-djangomaster
    - env: TOX_ENV=py36-djangomaster

addons:
  apt:
    packages:
    - xmlsec1

install:
    - pip install --upgrade pip setuptools tox virtualenv rstcheck

script:
    - tox -e $TOX_ENV
    - rstcheck README.rst

after_success:
    - pip install codecov
    - codecov -e TOX_ENV,TRAVIS_PYTHON_VERSION

notifications:
    email: false
