language: python

sudo: false

python:
  - 3.6

env:
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0


addons:
  apt:
    packages:
    - xmlsec1

install:
    - pip install --upgrade pip setuptools tox virtualenv rstcheck

script:
    - tox -e "d${DJANGO//.}-py${TRAVIS_PYTHON_VERSION//.}"
    - rstcheck README.rst

after_success:
    - pip install codecov
    - codecov -e TOX_ENV,TRAVIS_PYTHON_VERSION

notifications:
    email: false
